### ISSUE TITLE
Discussion tracking for ARIA Notification proposal

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria#1957]
During the most recent ARIA F2F meeting the ARIA Notification proposal was presented and there were a number of open questions that needed resolution to move forward.

The purpose of this issue is to create a list of those discussion points so that there can be a single unified issue where resolution of those topics are tracked and reported upon, rather than having to dive into various different issues or discussion threads.

- [x] [Does the notification API need to support Braille-specific notifications rather than identical notifications for speech and visibly rendered text?](https://github.com/w3c/aria/discussions/1958#discussioncomment-6200866)
- [x] [Does the notification API need to support speech markup/pronunciations (i.e. SSML or IPA)](https://github.com/w3c/aria/discussions/1958#discussioncomment-6223153)
- [x] [Guidance on fallback procedures (What to do if the platform/browser doesn't support the necessary API)](https://github.com/w3c/aria/discussions/1958#discussioncomment-6223219)
- [x] [Explain / identify guidance for expected (not required) screen reader interaction](https://github.com/w3c/aria/discussions/1958#discussioncomment-6223691)
- [x] [Referencing Arrays in the current spec appears confusing](https://github.com/w3c/aria/discussions/1958#discussioncomment-6223738)
- [ ] [notificationId: discussion points](https://github.com/w3c/aria/discussions/1958#discussioncomment-9653301)
- [ ] [Scoping / source](https://github.com/w3c/aria/discussions/1958#discussioncomment-9653368)
- [ ] [Interrupt & flushing](https://github.com/w3c/aria/discussions/1958#discussioncomment-9653385)
- [ ] [Understandability](https://github.com/w3c/aria/discussions/1958#discussioncomment-9653408)
- [ ] [IA2 Support](https://github.com/w3c/aria/discussions/1958#discussioncomment-9653452)
- [ ] [Avoiding pestering/annoyance of notifications](https://github.com/w3c/aria/discussions/1958#discussioncomment-10363453)

**Comment by alisonmaher** [comment]
@benbeaudry and I will be attending TPAC virtually from the Redmond area. @douggeoffray isn't registered but would be virtual from the Redmond. @spectranaut will it be required for Doug to register in order to attend the call for this topic?

**Comment by alisonmaher** [comment]
Since it is tough to tell in the list what has been resolved and what hasn't, I will be planning to open individual issues for various topics ahead of TPAC to help in framing our discussions there. I will plan to post the new issues to the topics noted above that they are related to so folks will know where to look for the new issues.

**Comment by alisonmaher** [comment]
I've put together a pre-read with a summary and status of `ariaNotify` ahead of TPAC, with a list of the Github issues I opened as part of the agenda: https://docs.google.com/document/d/1gwTSfZeT3xIB9k1nVgoLm0Cg64eODGHBDcvB-42xQ4k/edit?usp=sharing

**Comment by daniel-montalvo** [comment]
Thanks Alison.

 

I’ve just linked to this document from the agenda page 

https://github.com/w3c/aria/wiki/TPAC-2024-ARIA-Meetings

 

Let me know if that’s OK or you’d prefer something else.

 

Best.

 

--

Daniel Montalvo Charameli

Accessibility Specialist

W3C/WAI

**Comment by alisonmaher** [comment]
@daniel-montalvo that works great, thanks!

**Comment by alisonmaher** [comment]
Closing this issue since we are tracking these all as separate issues in the Github repo now
