### ISSUE TITLE
WAI-ARIA 1.3 FPWD HR tracker

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/aria#2139]
This issue tracks Wide Review comments for WAI-ARIA 1.3 FPWD

* [ ] [Security](https://github.com/w3c/security-request/issues/65)
* [ ] [Privacy}(https://github.com/w3cping/privacy-request/issues/131)
* [ ] [I18n](https://github.com/w3c/i18n-request/issues/225)
* [x] [Accessibility](https://github.com/w3c/a11y-request/issues/72) 
* [x] [TAG](https://github.com/w3ctag/design-reviews/issues/927)
